version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: yeoman-generator
    versions:
    - 5.0.0
    - 5.0.1
    - 5.1.0
  - dependency-name: normalize-url
    versions:
    - 5.3.0
